"""add is_system to user, remove tags from video, add tag and video_tags tables

Revision ID: cf4cb00effbb
Revises: dc63b77b98d8
Create Date: 2026-05-19 16:35:25.964022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf4cb00effbb'
down_revision = 'dc63b77b98d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_system', sa.Boolean(), nullable=True))

    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.VARCHAR(length=500), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_system')

    # ### end Alembic commands ###
